### ISSUE TITLE
Could not launch cold update process

### ISSUE THREAD

**Issue by robinwassen** [robinwassen/NAppUpdate2#1]
See: https://github.com/synhershko/NAppUpdate/issues/54

**Comment by robinwassen** [comment]
Received exception after the improved logging:

```
Could not launch cold update process
System.Exception: Launch process client: Failed to connect to named pipe
   at NAppUpdate.Framework.Utils.NauIpc.LaunchProcessAndSendDto(NauDto dto, ProcessStartInfo processStartInfo, String syncProcessName)
   at NAppUpdate.Framework.UpdateManager.ApplyUpdates(Boolean relaunchApplication, Boolean updaterDoLogging, Boolean updaterShowConsole)
```

Which means that the pipe state result is 0 here: https://github.com/robinwassen/NAppUpdate2/blob/4810eb9c7581139c74209938aa109e76ea8b0e9f/src/NAppUpdate.Framework/Utils/NauIpc.cs#L117

**Comment by robinwassen** [comment]
Which means that we should do another debug iteration where we fix the error handling in the ConnectPipe() method, because it is probably there something goes haywire.

**Comment by robinwassen** [comment]
There are two potential sources of the error that is being supressed at: https://github.com/robinwassen/NAppUpdate2/blob/97b5f60991d25c9e404f11cc3e719fa44753bd09/src/NAppUpdate.Framework/Utils/NauIpc.cs#L145

- Marshal.GetLastWin32Error() if state.result is 0
- Exception if ConnectNamedPipe() throws one

**Comment by robinwassen** [comment]
Same error message after #11 

```
Could not launch cold update process
System.Exception: Launch process client: Failed to connect to named pipe
 at NAppUpdate.Framework.Utils.NauIpc.LaunchProcessAndSendDto(NauDto dto, ProcessStartInfo processStartInfo, String syncProcessName)
 at NAppUpdate.Framework.UpdateManager.ApplyUpdates(Boolean relaunchApplication, Boolean updaterDoLogging, Boolean updaterShowConsole)
```

**Comment by robinwassen** [comment]
I got to see this problem with my own eyes for the first time, could not debug it but it took approximately 10 seconds before the exception was thrown.

Which leads me into that it is due to a timeout of the ManualResetEvent.

If a timeout occurs the whole `Marshal.GetLastWin32Error()` part is bypassed and therefore we don't get the error.

Need to redo the error handling so it is done even though it is a `ManualResetEvent` timeout.
